[package]
name = "heatmap-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
svg = "0.13.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenvy = "0.15"
